---
blackbird:
  image: quay.io/kwiksand/blackbird:1.1
#  ports:
#  - "8080:8080"
  volumes:
  - ./logs/:/application/logs
  - ./blackbird.conf:/application/blackbird.conf
  links:
  - mysql
mysql:
  image: percona:latest
  ports:
  - "3306:3306"
  volumes:
  - ./sql/:/docker-entrypoint-initdb.d # Prime the MySQL DB
  environment:
  - MYSQL_ROOT_PASSWORD=INSERT_PASSWORD_HERE
